providers:
  file:
    filename: /etc/traefik/esi-configuration.yaml
    watch: true


experimental:
  localPlugins:
    esi:
      moduleName: github.com/darkweak/go-esi

log:
  level: DEBUG

entryPoints:
  http:
    address: ":80"

accessLog: {}