version: '3.8'

services:
  traefik:
    image: traefik:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./go-esi:/plugins-local/src/github.com/darkweak/go-esi
      - ./traefik.yml:/traefik.yml
      - ./esi-configuration.yml:/esi-configuration.yml
    environment:
      GOPATH: /plugins-local
    ports:
      - 80:80
      - 8080:8080

  nginx:
    image: crazygoat/nginx-ssi-example
    labels:
      - traefik.http.routers.nginx.rule=Host(`domain.com`)
    volumes:
      - ./www:/var/www